# Generated by Django 5.1.1 on 2024-11-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.UniqueConstraint(fields=('data', 'hora', 'local'), name='unique_partida'),
        ),
    ]
