# Generated by Django 5.1.1 on 2024-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0004_partida_organizador_participacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
