# Generated by Django 5.1.1 on 2024-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0007_historicopartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='preco_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
