# Generated by Django 5.1.1 on 2024-12-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0010_partida_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='id_stripe',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='preco_stripe',
        ),
    ]
