# Generated by Django 5.1.1 on 2024-12-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0011_remove_partida_id_stripe_remove_partida_preco_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='preco_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
