# Generated by Django 5.1.1 on 2024-12-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0012_partida_id_stripe_partida_preco_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='pago',
        ),
        migrations.AddField(
            model_name='participacao',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
