# Generated by Django 5.1.1 on 2024-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avancado', 'Avancado')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='posicao',
            field=models.CharField(choices=[('Levantador', 'Levantador'), ('Oposto', 'Oposto'), ('Central', 'Central'), ('Libero', 'Libero'), ('Ponteiro', 'Ponteiro')], default=2, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rotacao',
            field=models.CharField(choices=[('5x1', '5x1'), ('6x0', '6x0'), ('4x2', '4x2')], default=2, max_length=3),
            preserve_default=False,
        ),
    ]
