# Generated by Django 5.1.1 on 2024-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_perfilusuario_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avancado', 'Avancado')], default='Iniciante', max_length=15),
        ),
    ]
