# Generated by Django 5.1.1 on 2024-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_perfilusuario_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
