# Generated by Django 5.1.1 on 2024-11-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_perfilusuario_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rotacao',
            field=models.CharField(choices=[('5x1', '5x1'), ('6x0', '6x0'), ('4x2', '4x2')], default='6x0', max_length=3),
        ),
    ]
