# Generated by Django 5.1.1 on 2024-12-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_perfilusuario_historico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='historico',
            new_name='historicos',
        ),
    ]
