# Generated by Django 5.1.1 on 2024-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_historico_perfilusuario_historicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
