# Generated by Django 5.1.1 on 2024-12-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_perfilusuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preco_stripe',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
