# Generated by Django 5.1.1 on 2024-12-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_perfilusuario_id_stripe_perfilusuario_preco_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='id_stripe',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='preco_stripe',
        ),
    ]
